-- Норвежские вакансии: срок жизни объявления и подписи профессий.
--
-- 1. source_expires_at / source_published_at — даты САМОГО объявления у NAV,
--    не нашей строки. У событийного источника updated_at не значит «вакансия
--    ещё жива»: запись лежит нетронутой месяцами (медианный срок жизни
--    объявления — 34 дня, p90 — 157). Снятие с публикации для NAV идёт по
--    expires и событиям INACTIVE, а не по семидневному правилу JobTech.
--
-- 2. occupation_labels для кодов с префиксом NO-. Префикс обязателен:
--    шведский SSYK и норвежский STYRK08 пересекаются по номерам с разным
--    смыслом (7113 у нас сейчас шведский betongarbetare, в STYRK08 это
--    Steinhoggere). Существующие шведские коды не трогаем — подписки
--    job_alerts остаются валидными.

alter table public.vacancies
  add column if not exists source_expires_at timestamptz,
  add column if not exists source_published_at timestamptz;

comment on column public.vacancies.source_expires_at is
  'Срок объявления у источника (NAV ad_content.expires). Основание для снятия с публикации у событийных источников.';
comment on column public.vacancies.source_published_at is
  'Дата публикации у источника. Страховка на случай пустого expires: NAV декларирует максимум 6 месяцев активности.';

create index if not exists vacancies_source_expiry_idx
  on public.vacancies (source_name, source_expires_at)
  where published;

insert into public.occupation_labels (isco_code, locale, label) values
  ('NO-7112', 'lv', 'Mūrnieks'),
  ('NO-7112', 'ru', 'Каменщик'),
  ('NO-7112', 'en', 'Bricklayer'),
  ('NO-7112', 'lt', 'Mūrininkas'),
  ('NO-7112', 'et', 'Müürsepp'),
  ('NO-7113', 'lv', 'Ceļu un zemes darbu strādnieks'),
  ('NO-7113', 'ru', 'Дорожно-строительный рабочий'),
  ('NO-7113', 'en', 'Civil works / groundworks labourer'),
  ('NO-7113', 'lt', 'Kelio ir žemės darbų darbininkas'),
  ('NO-7113', 'et', 'Tee- ja pinnasetööline'),
  ('NO-7114', 'lv', 'Betonētājs'),
  ('NO-7114', 'ru', 'Бетонщик'),
  ('NO-7114', 'en', 'Concrete worker'),
  ('NO-7114', 'lt', 'Betonuotojas'),
  ('NO-7114', 'et', 'Betoonitööline'),
  ('NO-7115', 'lv', 'Namdaris'),
  ('NO-7115', 'ru', 'Плотник'),
  ('NO-7115', 'en', 'Carpenter'),
  ('NO-7115', 'lt', 'Dailidė'),
  ('NO-7115', 'et', 'Puusepp'),
  ('NO-7119', 'lv', 'Ceļu un zemes darbu strādnieks'),
  ('NO-7119', 'ru', 'Дорожно-строительный рабочий'),
  ('NO-7119', 'en', 'Civil works / groundworks labourer'),
  ('NO-7119', 'lt', 'Kelio ir žemės darbų darbininkas'),
  ('NO-7119', 'et', 'Tee- ja pinnasetööline'),
  ('NO-7121', 'lv', 'Jumiķis'),
  ('NO-7121', 'ru', 'Кровельщик'),
  ('NO-7121', 'en', 'Roofer'),
  ('NO-7121', 'lt', 'Stogdengys'),
  ('NO-7121', 'et', 'Katusekatja'),
  ('NO-7122', 'lv', 'Grīdas un flīžu licējs'),
  ('NO-7122', 'ru', 'Укладчик полов и плитки'),
  ('NO-7122', 'en', 'Floor and tile layer'),
  ('NO-7122', 'lt', 'Grindų ir plytelių klojėjas'),
  ('NO-7122', 'et', 'Põranda- ja plaadipaigaldaja'),
  ('NO-7124', 'lv', 'Izolētājs'),
  ('NO-7124', 'ru', 'Изолировщик'),
  ('NO-7124', 'en', 'Insulation installer'),
  ('NO-7124', 'lt', 'Izoliuotojas'),
  ('NO-7124', 'et', 'Isolatsioonipaigaldaja'),
  ('NO-7125', 'lv', 'Stiklinieks'),
  ('NO-7125', 'ru', 'Стекольщик'),
  ('NO-7125', 'en', 'Glazier'),
  ('NO-7125', 'lt', 'Stiklius'),
  ('NO-7125', 'et', 'Klaassepp'),
  ('NO-7126', 'lv', 'Santehniķis'),
  ('NO-7126', 'ru', 'Сантехник'),
  ('NO-7126', 'en', 'Plumber'),
  ('NO-7126', 'lt', 'Santechnikas'),
  ('NO-7126', 'et', 'Torulukksepp'),
  ('NO-7127', 'lv', 'Aukstumiekārtu montieris'),
  ('NO-7127', 'ru', 'Монтажник холодильного оборудования'),
  ('NO-7127', 'en', 'Refrigeration technician'),
  ('NO-7127', 'lt', 'Šaldymo įrangos montuotojas'),
  ('NO-7127', 'et', 'Külmaseadmete paigaldaja'),
  ('NO-7131', 'lv', 'Krāsotājs'),
  ('NO-7131', 'ru', 'Маляр'),
  ('NO-7131', 'en', 'Painter'),
  ('NO-7131', 'lt', 'Dažytojas'),
  ('NO-7131', 'et', 'Maalritööline'),
  ('NO-7132', 'lv', 'Krāsotājs'),
  ('NO-7132', 'ru', 'Маляр'),
  ('NO-7132', 'en', 'Painter'),
  ('NO-7132', 'lt', 'Dažytojas'),
  ('NO-7132', 'et', 'Maalritööline'),
  ('NO-7133', 'lv', 'Fasādes strādnieks'),
  ('NO-7133', 'ru', 'Фасадчик'),
  ('NO-7133', 'en', 'Facade worker'),
  ('NO-7133', 'lt', 'Fasado darbininkas'),
  ('NO-7133', 'et', 'Fassaaditööline'),
  ('NO-7212', 'lv', 'Metinātājs'),
  ('NO-7212', 'ru', 'Сварщик'),
  ('NO-7212', 'en', 'Welder'),
  ('NO-7212', 'lt', 'Suvirintojas'),
  ('NO-7212', 'et', 'Keevitaja'),
  ('NO-7213', 'lv', 'Skārdnieks'),
  ('NO-7213', 'ru', 'Жестянщик'),
  ('NO-7213', 'en', 'Sheet metal worker'),
  ('NO-7213', 'lt', 'Skardininkas'),
  ('NO-7213', 'et', 'Plekksepp'),
  ('NO-7214', 'lv', 'Skārdnieks'),
  ('NO-7214', 'ru', 'Жестянщик'),
  ('NO-7214', 'en', 'Sheet metal worker'),
  ('NO-7214', 'lt', 'Skardininkas'),
  ('NO-7214', 'et', 'Plekksepp'),
  ('NO-7215', 'lv', 'Takelētājs'),
  ('NO-7215', 'ru', 'Такелажник'),
  ('NO-7215', 'en', 'Rigger'),
  ('NO-7215', 'lt', 'Takelažininkas'),
  ('NO-7215', 'et', 'Taageldaja'),
  ('NO-7222', 'lv', 'Instrumentu atslēdznieks'),
  ('NO-7222', 'ru', 'Слесарь-инструментальщик'),
  ('NO-7222', 'en', 'Toolmaker'),
  ('NO-7222', 'lt', 'Įrankininkas'),
  ('NO-7222', 'et', 'Tööriistalukksepp'),
  ('NO-7223', 'lv', 'Instrumentu atslēdznieks'),
  ('NO-7223', 'ru', 'Слесарь-инструментальщик'),
  ('NO-7223', 'en', 'Toolmaker'),
  ('NO-7223', 'lt', 'Įrankininkas'),
  ('NO-7223', 'et', 'Tööriistalukksepp'),
  ('NO-7231', 'lv', 'Automehāniķis'),
  ('NO-7231', 'ru', 'Автомеханик'),
  ('NO-7231', 'en', 'Vehicle mechanic'),
  ('NO-7231', 'lt', 'Automechanikas'),
  ('NO-7231', 'et', 'Automehaanik'),
  ('NO-7233', 'lv', 'Mehāniķis'),
  ('NO-7233', 'ru', 'Механик'),
  ('NO-7233', 'en', 'Mechanic'),
  ('NO-7233', 'lt', 'Mechanikas'),
  ('NO-7233', 'et', 'Mehaanik'),
  ('NO-7411', 'lv', 'Elektriķis'),
  ('NO-7411', 'ru', 'Электрик'),
  ('NO-7411', 'en', 'Electrician'),
  ('NO-7411', 'lt', 'Elektrikas'),
  ('NO-7411', 'et', 'Elektrik'),
  ('NO-7412', 'lv', 'Automātikas tehniķis'),
  ('NO-7412', 'ru', 'Техник по автоматике'),
  ('NO-7412', 'en', 'Automation technician'),
  ('NO-7412', 'lt', 'Automatikos technikas'),
  ('NO-7412', 'et', 'Automaatikatehnik'),
  ('NO-7413', 'lv', 'Elektrotehniķis'),
  ('NO-7413', 'ru', 'Электротехник'),
  ('NO-7413', 'en', 'Electrical technician'),
  ('NO-7413', 'lt', 'Elektrotechnikas'),
  ('NO-7413', 'et', 'Elektrotehnik'),
  ('NO-8211', 'lv', 'Montieris'),
  ('NO-8211', 'ru', 'Монтажник'),
  ('NO-8211', 'en', 'Fitter / assembler'),
  ('NO-8211', 'lt', 'Montuotojas'),
  ('NO-8211', 'et', 'Montöör'),
  ('NO-8219', 'lv', 'Montieris'),
  ('NO-8219', 'ru', 'Монтажник'),
  ('NO-8219', 'en', 'Fitter / assembler'),
  ('NO-8219', 'lt', 'Montuotojas'),
  ('NO-8219', 'et', 'Montöör'),
  ('NO-8322', 'lv', 'Šoferis'),
  ('NO-8322', 'ru', 'Водитель'),
  ('NO-8322', 'en', 'Driver'),
  ('NO-8322', 'lt', 'Vairuotojas'),
  ('NO-8322', 'et', 'Autojuht'),
  ('NO-8332', 'lv', 'Šoferis'),
  ('NO-8332', 'ru', 'Водитель'),
  ('NO-8332', 'en', 'Driver'),
  ('NO-8332', 'lt', 'Vairuotojas'),
  ('NO-8332', 'et', 'Autojuht'),
  ('NO-8342', 'lv', 'Speciālās tehnikas operators'),
  ('NO-8342', 'ru', 'Оператор спецтехники'),
  ('NO-8342', 'en', 'Heavy equipment operator'),
  ('NO-8342', 'lt', 'Specialiosios technikos operatorius'),
  ('NO-8342', 'et', 'Erimasinate operaator'),
  ('NO-8343', 'lv', 'Celtņa vadītājs'),
  ('NO-8343', 'ru', 'Крановщик'),
  ('NO-8343', 'en', 'Crane operator'),
  ('NO-8343', 'lt', 'Kranininkas'),
  ('NO-8343', 'et', 'Kraanajuht'),
  ('NO-8344', 'lv', 'Autoiekrāvēja vadītājs'),
  ('NO-8344', 'ru', 'Водитель погрузчика'),
  ('NO-8344', 'en', 'Forklift driver'),
  ('NO-8344', 'lt', 'Krautuvo vairuotojas'),
  ('NO-8344', 'et', 'Tõstukijuht'),
  ('NO-4321', 'lv', 'Noliktavas darbinieks'),
  ('NO-4321', 'ru', 'Складской рабочий'),
  ('NO-4321', 'en', 'Warehouse worker'),
  ('NO-4321', 'lt', 'Sandėlio darbuotojas'),
  ('NO-4321', 'et', 'Laotöötaja'),
  ('NO-4322', 'lv', 'Termināļa darbinieks'),
  ('NO-4322', 'ru', 'Работник терминала'),
  ('NO-4322', 'en', 'Terminal worker'),
  ('NO-4322', 'lt', 'Terminalo darbuotojas'),
  ('NO-4322', 'et', 'Terminalitöötaja'),
  ('NO-9333', 'lv', 'Termināļa darbinieks'),
  ('NO-9333', 'ru', 'Работник терминала'),
  ('NO-9333', 'en', 'Terminal worker'),
  ('NO-9333', 'lt', 'Terminalo darbuotojas'),
  ('NO-9333', 'et', 'Terminalitöötaja'),
  ('NO-9312', 'lv', 'Palīgstrādnieks'),
  ('NO-9312', 'ru', 'Разнорабочий'),
  ('NO-9312', 'en', 'General labourer'),
  ('NO-9312', 'lt', 'Pagalbinis darbininkas'),
  ('NO-9312', 'et', 'Abitööline'),
  ('NO-9313', 'lv', 'Palīgstrādnieks'),
  ('NO-9313', 'ru', 'Разнорабочий'),
  ('NO-9313', 'en', 'General labourer'),
  ('NO-9313', 'lt', 'Pagalbinis darbininkas'),
  ('NO-9313', 'et', 'Abitööline'),
  ('NO-9329', 'lv', 'Palīgstrādnieks'),
  ('NO-9329', 'ru', 'Разнорабочий'),
  ('NO-9329', 'en', 'General labourer'),
  ('NO-9329', 'lt', 'Pagalbinis darbininkas'),
  ('NO-9329', 'et', 'Abitööline'),
  ('NO-9629', 'lv', 'Palīgstrādnieks'),
  ('NO-9629', 'ru', 'Разнорабочий'),
  ('NO-9629', 'en', 'General labourer'),
  ('NO-9629', 'lt', 'Pagalbinis darbininkas'),
  ('NO-9629', 'et', 'Abitööline'),
  ('NO-8160', 'lv', 'Ražošanas operators'),
  ('NO-8160', 'ru', 'Оператор производства'),
  ('NO-8160', 'en', 'Production operator'),
  ('NO-8160', 'lt', 'Gamybos operatorius'),
  ('NO-8160', 'et', 'Tootmisoperaator'),
  ('NO-8114', 'lv', 'Betonētājs'),
  ('NO-8114', 'ru', 'Бетонщик'),
  ('NO-8114', 'en', 'Concrete worker'),
  ('NO-8114', 'lt', 'Betonuotojas'),
  ('NO-8114', 'et', 'Betoonitööline'),
  ('NO-3123', 'lv', 'Namdaris'),
  ('NO-3123', 'ru', 'Плотник'),
  ('NO-3123', 'en', 'Carpenter'),
  ('NO-3123', 'lt', 'Dailidė'),
  ('NO-3123', 'et', 'Puusepp')
on conflict (isco_code, locale) do update set label = excluded.label;
