-- Подписи профессий, которых не хватало в фильтре (24.08.2026).
--
-- Миграция 012 завела подписи для 22 кодов, реально встречавшихся в базе на
-- 15.08.2026. С тех пор импорт принёс новые, и в списке на главной висели
-- голые коды: «8342 (12)», «3113 (8)», «7114 (5)» — 23 пункта из 39, за ними
-- 56 вакансий. Названия взяты из официальной таксономии JobTech
-- (taxonomy.api.jobtechdev.se, ssyk-code-2012), а не придуманы по заголовкам
-- вакансий: 8342 это «Anläggningsmaskinförare m.fl.», 9610 —
-- «Renhållnings- och återvinningsarbetare» и так далее.
--
-- lt/et переведены для полноты и не показываются, пока эти локали за
-- ENABLED_LOCALES.

insert into public.occupation_labels (isco_code, locale, label) values
  ('8342', 'lv', 'Ceļu būves mašīnu operators'),
  ('8342', 'ru', 'Машинист спецтехники'),
  ('8342', 'en', 'Construction machine operator'),
  ('8342', 'lt', 'Statybos mašinų operatorius'),
  ('8342', 'et', 'Ehitusmasina juht'),
  ('3113', 'lv', 'Elektrotehnikas tehniķis'),
  ('3113', 'ru', 'Электротехник'),
  ('3113', 'en', 'Electrical engineering technician'),
  ('3113', 'lt', 'Elektrotechnikos technikas'),
  ('3113', 'et', 'Elektrotehnika tehnik'),
  ('7114', 'lv', 'Ceļu būves strādnieks'),
  ('7114', 'ru', 'Дорожный рабочий'),
  ('7114', 'en', 'Civil engineering worker'),
  ('7114', 'lt', 'Kelių tiesimo darbininkas'),
  ('7114', 'et', 'Teedeehitustööline'),
  ('7113', 'lv', 'Betonētājs'),
  ('7113', 'ru', 'Бетонщик'),
  ('7113', 'en', 'Concrete worker'),
  ('7113', 'lt', 'Betonuotojas'),
  ('7113', 'et', 'Betoonitööline'),
  ('7231', 'lv', 'Automehāniķis'),
  ('7231', 'ru', 'Автомеханик'),
  ('7231', 'en', 'Vehicle mechanic'),
  ('7231', 'lt', 'Automechanikas'),
  ('7231', 'et', 'Automehaanik'),
  ('9610', 'lv', 'Atkritumu apsaimniekošanas darbinieks'),
  ('9610', 'ru', 'Работник вывоза мусора'),
  ('9610', 'en', 'Refuse and recycling worker'),
  ('9610', 'lt', 'Atliekų tvarkymo darbuotojas'),
  ('9610', 'et', 'Jäätmekäitlustööline'),
  ('8129', 'lv', 'Metālapstrādes iekārtu operators'),
  ('8129', 'ru', 'Оператор металлообрабатывающего оборудования'),
  ('8129', 'en', 'Metal processing machine operator'),
  ('8129', 'lt', 'Metalo apdirbimo įrenginių operatorius'),
  ('8129', 'et', 'Metallitöötlusseadme operaator'),
  ('8343', 'lv', 'Celtņa operators'),
  ('8343', 'ru', 'Крановщик'),
  ('8343', 'en', 'Crane operator'),
  ('8343', 'lt', 'Krano operatorius'),
  ('8343', 'et', 'Kraanajuht'),
  ('8212', 'lv', 'Elektroiekārtu montētājs'),
  ('8212', 'ru', 'Сборщик электрооборудования'),
  ('8212', 'en', 'Electrical equipment assembler'),
  ('8212', 'lt', 'Elektros įrangos surinkėjas'),
  ('8212', 'et', 'Elektriseadmete koostaja'),
  ('2320', 'lv', 'Arodpriekšmetu skolotājs'),
  ('2320', 'ru', 'Преподаватель профессиональных предметов'),
  ('2320', 'en', 'Vocational teacher'),
  ('2320', 'lt', 'Profesinių dalykų mokytojas'),
  ('2320', 'et', 'Kutseõpetaja'),
  ('7413', 'lv', 'Sadales tīklu elektriķis'),
  ('7413', 'ru', 'Электрик распределительных сетей'),
  ('7413', 'en', 'Distribution electrician'),
  ('7413', 'lt', 'Skirstomųjų tinklų elektrikas'),
  ('7413', 'et', 'Jaotusvõrgu elektrik'),
  ('7223', 'lv', 'Metālapstrādes darbgaldu operators'),
  ('7223', 'ru', 'Оператор металлорежущих станков'),
  ('7223', 'en', 'Metalworking machine operator'),
  ('7223', 'lt', 'Metalo staklių operatorius'),
  ('7223', 'et', 'Metallitöötluspingi operaator'),
  ('8171', 'lv', 'Celulozes ražošanas operators'),
  ('8171', 'ru', 'Оператор целлюлозного производства'),
  ('8171', 'en', 'Pulp process operator'),
  ('8171', 'lt', 'Celiuliozės gamybos operatorius'),
  ('8171', 'et', 'Tselluloositootmise operaator'),
  ('8191', 'lv', 'Siltuma un ūdensapgādes operators'),
  ('8191', 'ru', 'Оператор тепло- и водоснабжения'),
  ('8191', 'en', 'Heating and water plant operator'),
  ('8191', 'lt', 'Šilumos ir vandens tiekimo operatorius'),
  ('8191', 'et', 'Sooja- ja veevärgi operaator'),
  ('8329', 'lv', 'Citi transportlīdzekļu vadītāji'),
  ('8329', 'ru', 'Прочие водители'),
  ('8329', 'en', 'Other vehicle drivers'),
  ('8329', 'lt', 'Kiti transporto priemonių vairuotojai'),
  ('8329', 'et', 'Muud sõidukijuhid'),
  ('2143', 'lv', 'Elektroinženieris'),
  ('2143', 'ru', 'Инженер-электротехник'),
  ('2143', 'en', 'Electrical engineer'),
  ('2143', 'lt', 'Elektros inžinierius'),
  ('2143', 'et', 'Elektriinsener'),
  ('3339', 'lv', 'Citi starpnieki'),
  ('3339', 'ru', 'Прочие посредники'),
  ('3339', 'en', 'Other business agents'),
  ('3339', 'lt', 'Kiti tarpininkai'),
  ('3339', 'et', 'Muud vahendajad'),
  ('5132', 'lv', 'Bārmenis'),
  ('5132', 'ru', 'Бармен'),
  ('5132', 'en', 'Bartender'),
  ('5132', 'lt', 'Barmenas'),
  ('5132', 'et', 'Baarmen'),
  ('3313', 'lv', 'Grāmatvedis'),
  ('3313', 'ru', 'Бухгалтер'),
  ('3313', 'en', 'Accounting associate'),
  ('3313', 'lt', 'Buhalteris'),
  ('3313', 'et', 'Raamatupidaja'),
  ('1360', 'lv', 'Būvniecības ekspluatācijas vadītājs'),
  ('1360', 'ru', 'Руководитель строительной эксплуатации'),
  ('1360', 'en', 'Construction operations manager'),
  ('1360', 'lt', 'Statybos eksploatacijos vadovas'),
  ('1360', 'et', 'Ehituse käidujuht'),
  ('5152', 'lv', 'Namu pārzinis'),
  ('5152', 'ru', 'Управляющий зданием'),
  ('5152', 'en', 'Building caretaker'),
  ('5152', 'lt', 'Pastato prižiūrėtojas'),
  ('5152', 'et', 'Majahaldur'),
  ('3121', 'lv', 'Būvdarbu vadītājs'),
  ('3121', 'ru', 'Прораб'),
  ('3121', 'en', 'Construction supervisor'),
  ('3121', 'lt', 'Statybos darbų vadovas'),
  ('3121', 'et', 'Ehitustööde juhataja'),
  ('1230', 'lv', 'Administrācijas un plānošanas vadītājs'),
  ('1230', 'ru', 'Руководитель администрации и планирования'),
  ('1230', 'en', 'Administration and planning manager'),
  ('1230', 'lt', 'Administravimo ir planavimo vadovas'),
  ('1230', 'et', 'Haldus- ja planeerimisjuht')
on conflict (isco_code, locale) do update set label = excluded.label;
